apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-deployment-be-dev
 namespace: development
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: be-cilist-dev
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 20