apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-prod
  namespace: production
  labels: 
    app: mysql-prod
spec:
  serviceName: mysql-stateful-service-prod
  replicas: 3
  selector:
    matchLabels:
      app: mysql-prod
  template:
    metadata:
      labels:
        app: mysql-prod
  volumeClaimTemplates:
    - metadata:
        name: mysql-stateful-volume-claim-prod
        namespace: production
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      name: mysql-prod
      namespace: production
      labels:
        app: mysql-prod
    spec:
      containers:
      - name: mysql-prod
        image: ramses01/cilist-database:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret-db-prod
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db-prod
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db-prod
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-configmap-prod
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-stateful-volume-claim-prod
          mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-data
      #   volumeClaimTemplates:
      #     name: mysql-stateful-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-service-prod
  namespace: production
spec:
  selector:
     app: mysql-prod
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
    





